#!/bin/bash

set -u
set -e

. "$plugin_dir/php_functions"
. "$plugin_dir/functions"

# Installs everything from the PHP stack
. "$plugin_dir/php_setup"

# Installs drupal-specific content
install_libs "lib/drush-5.8;drush"
config_drush
install_drupal