#!/bin/bash

set -u
set -e

. "$plugin_dir/php-functions"
. "$plugin_dir/functions"

# Installs everything from the PHP stack
. "$plugin_dir/php-setup"

# Installs drupal-specific content
install_lib "drush"
config_drush
install_drupal